### PR TITLE
Conf: rm sentry errors to kevinlin

### PR DESCRIPTION
**Pull request by thomascharbonnel**
There is most likely a more clever way to do this (env var…), but hey that's better than nothing!

### CODE REVIEW

**Comment by LINKIWI** [comment]
This is deliberate.

**Comment by thomascharbonnel** [comment]
It's a noble intention to keep error logs to improve the program, but it might feel like spying, and that's a bit touchy for a geolocation app. Maybe we could give the user the option to opt-in?

**Comment by LINKIWI** [comment]
As the code is open source, you're more than welcome to fork the codebase to remove the URL or point it at your own server(s).

**Comment by thomascharbonnel** [comment]
Fair point

**Pull request closed without merging**
